name: Docker Image CI
on:
  push:
    branches:
    - master
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Gen image tag
      run: |
        if [[ $GITHUB_REF == 'refs/tags/'* ]]; then
          TAGS='["wei840222/github-releases-notifier:latest","wei840222/github-releases-notifier:'${GITHUB_REF/refs\/tags\//}'"]'
        else
          TAGS='["wei840222/github-releases-notifier:latest"]'
        fi
        echo '::set-output name=tags::'$TAGS
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: ${{ fromJson(steps.gen_tags.outputs.tags) }}
